#!/bin/bash
# ============LICENSE_START======================================================= 
# org.onap.vvp/gitlab
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.

set -x

# Fix GitLab permissions
if id -u git; then
	# Fix data storage
	chown -R git:git /var/opt/gitlab/.ssh
	chown -R git:git /var/opt/gitlab/.gitconfig
	chown -R git:git /var/opt/gitlab/git-data
	chown -R git:git /var/opt/gitlab/gitlab-ci/builds
	chown -R git:git /var/opt/gitlab/gitlab-git-http-server
	chown -R git:git /var/opt/gitlab/gitlab-rails
	chown -R git:git /var/opt/gitlab/gitlab-shell

	# Fix log storage
	chown git /var/log/gitlab/gitlab-git-http-server
	chown git /var/log/gitlab/gitlab-rails
	chown git /var/log/gitlab/gitlab-shell
	chown git /var/log/gitlab/sidekiq
	chown git /var/log/gitlab/unicorn
	chown gitlab-psql /var/log/gitlab/postgresql
	chown gitlab-redis /var/log/gitlab/redis

	# Update log files
	chown -R git:git /var/log/gitlab/gitlab-rails/*.log
	chown -R git:git /var/log/gitlab/gitlab-shell/*.log
	chown -R git:git /var/log/gitlab/unicorn/*.log
fi

# Fix nginx buffering directory permission
if id -u gitlab-www; then
	chown -R gitlab-www:gitlab-www /var/opt/gitlab/nginx/*_temp
fi

# Fix database storage
if id -u gitlab-psql; then
	chown -R gitlab-psql:gitlab-psql /var/opt/gitlab/postgresql
fi

# Fix redis storage
if id -u gitlab-redis; then
	chown gitlab-redis:gitlab-redis /var/opt/gitlab/redis
fi
